- hosts: localhost
  become: true

  tasks:
    - name: log into docker hub registry
      docker_login:
        email: "aida.liko@yahoo.com"
        username: "123456odi"
        password: "Admin1234"
       
    - name: ensure a container is running
      docker_container:
        name: trgproject
        state: started
        image: "123456odi/trgproject:latest"
        restart_policy: always
        pull: true
        ports:
          - "127.0.0.1:8087:8087"